#!/bin/bash

# Automate the retrieval of data for multiple Pokémon and store it in separate files.

# create a directory to sore all pokemon json files
DATA_DIR="pokemon_data"
mkdir -p "$DATA_DIR"

# list pokemon
POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

# loop through each pokemon
for pokemon in "${POKEMONS[@]}"; do 
    echo "Fetching data for $pokemon..."

    # API URL 
    URL="https://pokeapi.co/api/v2/pokemon/$pokemon"

    # fetch data and save to file
    curl -s -f "$URL" -o "$DATA_DIR/$pokemon.json"

    # check if curl succeeded
    if [ $? -eq 0 ]; then
        echo "Saved data to $DATA_DIR/$pokemon.json"
    else
        echo "Failed to fetch data for $pokemon" >> errors.txt
    fi 

        # wait 1 second to avoid rate-limiting
    sleep 1
done